### PR TITLE
First part of the Java 8 + Maven refactor

### PR DESCRIPTION
**Pull request by wilderrodrigues**
This PR makes the KVM hypervisor plugin Maven compliant

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Ping @borisroman @michaelandersen @miguelaferreira @bheuvel 

I already did the following tests:
- Cleaned the Maven repository
- Built the source
- Generated and Installed RPMs
- Deployed DC
- Deployed VM on isolated network

Will now run some integration tests. Will keep you updated.

**Comment by borisroman** [comment]
go build

**Comment by wilderrodrigues** [comment]
Guys,

Build is fine and I fixed the issue with the classpath. The root cause was the KVM Investigator class name, which should be camel case.

**Comment by miguelaferreira** [comment]
Can I merge this @wilderrodrigues?

**Comment by wilderrodrigues** [comment]
yes, @miguelaferreira . Please, merge all PRs with Maven refactor in the title.

I pasted the test results here -> https://github.com/MissionCriticalCloud/cosmic/pull/21

it's valid for all the PRs I created this afternoon and we need them all in in order to move on.

Thanks!

**Pull request merged**
