### PR TITLE
Remove unused vif drivers

### PR DESCRIPTION
**Pull request by remibergsma**
Two drivers that are unused in Cosmic.
- `IvsVifDriver` was part of BigSwitch
- `DirectVifDriver` was part of LXC
  Both are now gone and since this also includes some duplicate code I propose to ditch this too.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:52 min (Wall Clock)
[INFO] Finished at: 2016-05-13T21:19:02+02:00
[INFO] Final Memory: 73M/738M
[INFO] ------------------------------------------------------------------------
```

Ping @bheuvel @borisroman @wilderrodrigues

### CODE REVIEW

**Comment by remibergsma** [comment]
Integration tests: https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-tracking-repo-branch-build/78

**Comment by remibergsma** [comment]
The Jenkins build seems to hang. Any idea how to trigger rebuild? Tries force-push and close/open but didn't work.

**Comment by remibergsma** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by remibergsma** [comment]
Integration test results: https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-tracking-repo-branch-build/78/
Three tests failed, seem unrelated but weird that tests keep failing. What do you think @borisroman? Can't be related to PR I'd say.

**Comment by remibergsma** [comment]
Same 3 tests fail as on other PRs:
screen shot 2016-05-22 at 19 39 08 pm

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by wilderrodrigues** [comment]
go build

**Pull request merged**
